web:
  image: nginx:latest
  ports:
  - "8080:80"
  volumes:
  - ./:/home/www/rabbitmq-php.com
  - ./site.conf:/etc/nginx/conf.d/000_site.conf
  links:
  - php
php:
  image: php:7-fpm
  volumes:
  - ./:/home/www/rabbitmq-php.com